[project]
name = "oncall-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
    "django-environ>=0.12.0",
    "gunicorn>=23.0.0",
    "uvicorn[standard]>=0.35.0",
]
