# Generated by Django 5.2.5 on 2025-09-02 14:54

from django.db import migrations
from django.utils import timezone
from datetime import timedelta
import random


def populate_timestamps(apps, schema_editor):
    """
    Populate created and last_modified fields for existing records with fake but logical dates.
    """
    Shift = apps.get_model('records', 'Shift')
    TimeEntry = apps.get_model('records', 'TimeEntry')
    
    # Update Shifts first
    for shift in Shift.objects.all():
        # Set created to shift date + random time (8-18 hours on that day)
        created_time = timezone.datetime.combine(
            shift.date, 
            timezone.datetime.min.time().replace(
                hour=random.randint(8, 18),
                minute=random.randint(0, 59)
            )
        )
        created_time = timezone.make_aware(created_time)
        
        # Set last_modified to created + 0-7 days (most shifts modified shortly after creation)
        last_modified = created_time + timedelta(days=random.randint(0, 7), hours=random.randint(0, 23))
        
        Shift.objects.filter(pk=shift.pk).update(
            created=created_time,
            last_modified=last_modified
        )
    
    # Update TimeEntries
    for entry in TimeEntry.objects.all():
        # Set created to shift's created time + 0-24 hours (entries added on or shortly after shift creation)
        shift_created = entry.shift.created
        created_time = shift_created + timedelta(hours=random.randint(0, 24), minutes=random.randint(0, 59))
        
        # Set last_modified to created + 0-3 days (entries rarely modified after creation)
        last_modified = created_time + timedelta(days=random.randint(0, 3), hours=random.randint(0, 12))
        
        TimeEntry.objects.filter(pk=entry.pk).update(
            created=created_time,
            last_modified=last_modified
        )


def reverse_populate_timestamps(apps, schema_editor):
    """
    Reverse migration - set timestamps to None (though fields will be removed anyway)
    """
    # No need to do anything - the fields will be removed in the reverse of 0002
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_shift_created_shift_last_modified_timeentry_created_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_timestamps, reverse_populate_timestamps),
    ]
