# Generated by Django 5.2.5 on 2025-09-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20250902_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shift',
            new_name='Block',
        ),
        migrations.RenameField(
            model_name='timeentry',
            old_name='shift',
            new_name='block',
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set(),
        ),
    ]
