# Generated by Django 5.2.5 on 2025-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_shift_block_rename_shift_timeentry_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='claim',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total claim hours for this block', max_digits=5, null=True),
        ),
    ]
