# Generated by Django 5.2.5 on 2025-09-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_block_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='claim',
        ),
    ]
