# Generated by Django 5.2.5 on 2025-09-02 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_replace_day_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(help_text='Donor identifier (can be numeric or text)', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional donor name', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this donor')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LabTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lab task name/description', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the lab task')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(help_text='Unique recipient identifier', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional recipient name', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this recipient')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient'), ('lab_task', 'Lab Task')], max_length=20)),
                ('entity_id', models.CharField(help_text='ID of the watched entity', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notes about watching this entity during this block')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='records.block')),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'Watches',
                'unique_together': {('block', 'entity_type', 'entity_id')},
            },
        ),
    ]
