# Generated by Django 5.2.5 on 2025-09-03 08:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_donor_labtask_recipient_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient'), ('lab_task', 'Lab Task')], max_length=20)),
                ('entity_id', models.CharField(help_text='ID of the assigned entity', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notes about this assignment during this block')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='records.block')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'unique_together': {('block', 'entity_type', 'entity_id')},
            },
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
