# Generated by Django 5.2.5 on 2025-09-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_rename_watch_to_assignment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='TimeBlock',
        ),
    ]
