# Generated by Django 5.2.5 on 2025-09-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_populate_assignment_colors_icons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeentry',
            old_name='block',
            new_name='timeblock',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='color',
            field=models.CharField(default='primary', help_text='Bootstrap color for the assignment badge', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='icon',
            field=models.CharField(default='bi-person-fill', help_text='Bootstrap icon class', max_length=50),
        ),
    ]
