# Generated by Django 5.2.5 on 2025-09-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_rename_block_timeentry_timeblock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='block',
            new_name='timeblock',
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('timeblock', 'entity_type', 'entity_id')},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this assignment during this time block'),
        ),
    ]
