# Generated by Django 5.2.5 on 2025-09-03 23:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_rename_task_to_tasktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('signed_off_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this sign-off')),
                ('signed_off_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signoffs_given', to='records.oncallstaff')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_signoffs', to='records.oncallstaff')),
            ],
            options={
                'verbose_name': 'Monthly Sign-Off',
                'verbose_name_plural': 'Monthly Sign-Offs',
                'ordering': ['-year', '-month', 'staff__assignment_id'],
                'unique_together': {('staff', 'year', 'month')},
            },
        ),
    ]
