# Generated by Django 5.2.5 on 2025-09-04 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_monthlysignoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReportSignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('signed_off_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Notes about this report sign-off')),
                ('total_staff_count', models.IntegerField(help_text='Number of staff included in this report')),
                ('total_hours', models.DecimalField(decimal_places=2, help_text='Total hours for all staff', max_digits=8)),
                ('total_claims', models.DecimalField(decimal_places=2, help_text='Total claims for all staff', max_digits=10)),
                ('signed_off_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_signoffs_given', to='records.oncallstaff')),
            ],
            options={
                'verbose_name': 'Monthly Report Sign-Off',
                'verbose_name_plural': 'Monthly Report Sign-Offs',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
