# Generated by Django 5.2.5 on 2025-09-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_add_oncall_type_to_timeblock'),
        ('records', '0021_monthlyreportsignoff'),
    ]

    operations = [
    ]
