# Generated by Django 5.2.5 on 2025-09-04 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_merge_20250904_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rota entries',
                'ordering': ['date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='RotaShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seniority_level', models.CharField(choices=[('trainee', 'Trainee'), ('oncall', 'On-Call'), ('senior', 'Senior')], max_length=10)),
                ('shift_type', models.CharField(choices=[('normal', 'Normal'), ('nhsp', 'NHSP')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this shift')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('rota_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='records.rotaentry')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.oncallstaff')),
            ],
            options={
                'ordering': ['seniority_level', 'staff__assignment_id'],
                'unique_together': {('rota_entry', 'staff', 'shift_type')},
            },
        ),
    ]
