# Generated by Django 5.2.5 on 2025-09-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_rotaentry_rotashift'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rotashift',
            unique_together={('rota_entry', 'staff')},
        ),
        migrations.AddField(
            model_name='rotaentry',
            name='shift_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('nhsp', 'NHSP')], default='normal', help_text='Type of shift for the entire day', max_length=10),
        ),
        migrations.RemoveField(
            model_name='rotashift',
            name='shift_type',
        ),
    ]
