# Generated by Django 5.2.5 on 2025-09-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_alter_rotashift_unique_together_rotaentry_shift_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallstaff',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Hex color code for this staff member (e.g. #ff5733)', max_length=7),
        ),
    ]
