# Generated by Django 5.2.5 on 2025-09-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_oncallstaff_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallstaff',
            name='seniority_level',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('oncall', 'On-Call'), ('senior', 'Senior')], default='trainee', help_text='Seniority level of this staff member', max_length=10),
        ),
    ]
