# Generated by Django 5.2.5 on 2025-09-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_oncallstaff_seniority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oncallstaff',
            name='seniority_level',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('oncall', 'On-Call'), ('senior', 'Senior Cover')], default='trainee', help_text='Seniority level of this staff member', max_length=10),
        ),
        migrations.AlterField(
            model_name='rotashift',
            name='seniority_level',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('oncall', 'On-Call'), ('senior', 'Senior Cover')], max_length=10),
        ),
    ]
