# Generated by Django 5.2.5 on 2025-09-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0028_alter_oncallstaff_seniority_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncallstaff',
            options={'verbose_name': 'Staff Member', 'verbose_name_plural': 'Staff Members'},
        ),
    ]
