# Generated by Django 5.2.5 on 2025-09-05 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0029_alter_oncallstaff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oncallstaff',
            options={'verbose_name': 'On-call Staff', 'verbose_name_plural': 'On-call Staff'},
        ),
    ]
