# Generated by Django 5.2.5 on 2025-09-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0030_alter_oncallstaff_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labtask',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='claim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='oncall_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('nhsp', 'NHSP')], default='normal', max_length=20),
        ),
    ]
