# Generated by Django 5.2.5 on 2025-09-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0031_alter_labtask_description_alter_labtask_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
