# Generated by Django 5.2.5 on 2025-09-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0033_replace_detail_with_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('title', models.CharField(help_text='Name of the bank holiday', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('bunting', models.BooleanField(default=False, help_text='Whether bunting is required')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank Holiday',
                'verbose_name_plural': 'Bank Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='rotaentry',
            name='shift_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('nhsp', 'NHSP')], default='normal', max_length=10),
        ),
    ]
