# Generated by Django 5.2.5 on 2025-09-06 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0034_bankholiday_alter_rotaentry_shift_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankholiday',
            name='bunting',
        ),
        migrations.RemoveField(
            model_name='bankholiday',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bankholiday',
            name='updated',
        ),
    ]
